### ISSUE TITLE
Could not find a package configuration file provided by "ament_cmake_core" 

### ISSUE THREAD

**Issue by bionade24** [ros/ros_environment#15]
ROS Melodic with python3, from the official melodic-devel branches
```
CMake Error at CMakeLists.txt:3 (find_package):
  By not providing "Findament_cmake_core.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ament_cmake_core", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake_core"
  with any of the following names:

    ament_cmake_coreConfig.cmake
    ament_cmake_core-config.cmake

  Add the installation prefix of "ament_cmake_core" to CMAKE_PREFIX_PATH or
  set "ament_cmake_core_DIR" to a directory containing one of the above
  files.  If "ament_cmake_core" provides a separate development package or
  SDK, be sure it has been installed.

```

**Comment by dirk-thomas** [comment]
ROS Melodic is a ROS 1 distribution. `ament_cmake_core` on the other hand is a ROS 2 package. It seems like you are mixing something but without any further context it is impossible to say what it is.

**Comment by bionade24** [comment]
I'm the AUR maintainer. By using the latest release package of this Repo I get this. 
Similar issue here: https://github.com/ros/class_loader/issues/125

**Comment by bionade24** [comment]
@dirk-thomas So the 2.x releases are for ROS2? Why aren't those in the ROS2 group? Can you please highlight this?

**Comment by dirk-thomas** [comment]
This repository has different branches for different ROS distros - both ROS 1 and ROS 2. Each branch will only work for the distro it is targeting.

> Why aren't those in the ROS2 group?

Are you referring to the GitHub org unit: https://github.com/ros2 ? Not all ROS 2 related code is hosted in that org unit. As in this case the code can be hosted in the same repository as the ROS 1 equivalent - commonly on a different branch.

**Comment by dirk-thomas** [comment]
> By using the latest release package of this Repo I get this.

Please be more specific what exact version of the package you are using. It sounds like you are mixing source code intended for different ROS distributions but without more information that is impossible to tell.

**Comment by bionade24** [comment]
D

> This repository has different branches for different ROS distros - both ROS 1 and ROS 2. Each branch will only work for the distro it is targeting.
> 
> > Why aren't those in the ROS2 group?
> 
> Are you referring to the GitHub org unit: https://github.com/ros2 ? Not all ROS 2 related code is hosted in that org unit. As in this case the code can be hosted in the same repository as the ROS 1 equivalent - commonly on a different branch.

I didn't know that, fixed my sources and will close the issue. But please communicate it in the `README.md`

**Comment by akshay-ka** [comment]
I have installed ubuntu 24.04 OS  on my machine and using ROS `jazzy` version. 

I'm facing the same error when i run the command `colcon build --cmake-clean-cache`.


Any solution for this failure ?
