### ISSUE TITLE
non-obvious ordering

### ISSUE THREAD

**Issue by LucidOne** [ros/ros_environment#20]
Shouldn't these env-hooks be named 01.*

**Comment by dirk-thomas** [comment]
Can you please elaborate why you think the names should be changed.

**Comment by LucidOne** [comment]
It is not obvious if `1.ros_etc_dir.sh` is intended to be executed before or after `05.catkin_make.bash`

```
turtlebot@turtlebot:~$ ls -la /opt/ros/kinetic/etc/catkin/profile.d/
total 96
drwxr-xr-x 2 root root 4096 Oct 30 04:55 .
drwxr-xr-x 3 root root 4096 Oct 18 02:05 ..
-rw-r--r-- 1 root root 2873 Jun  7 13:55 05.catkin_make.bash
-rw-r--r-- 1 root root 2786 Jun  7 13:55 05.catkin_make_isolated.bash
-rw-r--r-- 1 root root  130 Oct 30 04:39 05.environment.sh
-rw-r--r-- 1 root root  237 Jun  8 01:21 10.rosbuild.sh
-rw-r--r-- 1 root root  122 Aug 23  2018 10.roslaunch.sh
-rw-r--r-- 1 root root  250 Jun  8 08:13 15.rocon_app.bash
-rw-r--r-- 1 root root  249 Jun  8 08:13 15.rocon_app.tcsh
-rw-r--r-- 1 root root  247 Jun  8 08:13 15.rocon_app.zsh
-rw-r--r-- 1 root root  203 Jun  8 01:23 15.rosbash.bash
-rw-r--r-- 1 root root  203 Jun  8 01:23 15.rosbash.fish
-rw-r--r-- 1 root root  203 Jun  8 01:23 15.rosbash.tcsh
-rw-r--r-- 1 root root  201 Jun  8 01:23 15.rosbash.zsh
-rw-r--r-- 1 root root  243 Jun  8 08:58 15.rospair.bash
-rw-r--r-- 1 root root  292 Jun  7 21:19 1.ros_distro.sh
-rw-r--r-- 1 root root  246 Jun  7 21:19 1.ros_etc_dir.sh
-rw-r--r-- 1 root root 1052 Jun  7 21:19 1.ros_package_path.sh
-rw-r--r-- 1 root root   85 Jun  7 21:19 1.ros_version.sh
-rw-r--r-- 1 root root  805 Oct 28 02:44 20.network_autoconfig.sh
-rw-r--r-- 1 root root 1067 Aug 23  2018 20.transform.bash
-rw-r--r-- 1 root root  893 Aug 27 19:50 25.turtlebot-navigation.sh
-rw-r--r-- 1 root root 1965 Aug 27 19:17 25.turtlebot.sh
-rw-r--r-- 1 root root  895 Jul 14  2017 99.roslisp.sh
```

**Comment by dirk-thomas** [comment]
I understand the "not-obvious" point. `1.*` should be ordered *before* `10.*` / `15.*`.

So just to clarify: does the current naming pose a problem for you anywhere?

**Comment by LucidOne** [comment]
I don't think it's breaking anything, but I have a rule I misnamed because of the sort order.
https://github.com/LucidOne/robot_systemd/blob/master/env-hooks/00.environment.sh
I'm actually more concerned about trying to name a rule 100.whatever, but I'll file that as a bug against roslisp not actually needing 99

**Comment by dirk-thomas** [comment]
> I'm actually more concerned about trying to name a rule 100.

I would assume this still would work as intended - being sources after all since digit / double digit scripts - if the numbers are consistent followed by a for.

**Comment by LucidOne** [comment]
Well I guess if it ain't fixed don't break it.
Thanks for your time!

**Comment by dirk-thomas** [comment]
I am just trying to understand the use case / scope. Renaming the scripts to use two digits to make them more intuitive sounds reasonable to me. Would you mind creating a pull request to rename the environment hooks?

**Comment by LucidOne** [comment]
I'm happy to create a pull request just to satisfy my OCD. :slightly_smiling_face:
I'll send it in tomorrow.
