### ISSUE TITLE
Variable ROS_PYTHON_VERSION not exported for Kinetic

### ISSUE THREAD

**Issue by jonazpiazu** [ros/ros_environment#21]
Hi,
I cannot see the variable `ROS_PYTHON_VERSION` correctly defined for Kinetic (it is actually undefined) while it works properly for Melodic.
Can be easily reproduced using the Docker images:

```
$ docker run -it --rm ros:melodic bash -c 'echo $ROS_PYTHON_VERSION'
2

$ docker run -it --rm ros:kinetic bash -c 'echo $ROS_PYTHON_VERSION'

-- no output ---
```

Actually the files where the variables are defined are there for the Melodic version:

```
$ docker run -it --rm ros:melodic bash -c "find /opt/ros/ -name '*ros_python_version*'"
/opt/ros/melodic/share/ros_environment/catkin_env_hook/1.ros_python_version.sh
/opt/ros/melodic/etc/catkin/profile.d/1.ros_python_version.sh
```

But not for the Kinetic version:

```
$ docker run -it --rm ros:kinetic bash -c "find /opt/ros/ -name '*ros_python_version*'"

-- no output ---
```

In case you are wondering, but images have the corresponding `ros-ROSDISTRO-ros-environment` packages installed.

Thanks

**Comment by dirk-thomas** [comment]
The `ROS_PYTHON_VERSION` hook was added in #9 for Kinetic. Since then there has been no new release of this package. That is why the Debian package doesn't contain the environment variable.

I just made a new release (see ros/rosdistro#23032) so with the next sync the env var should be available.
