### ISSUE TITLE
This package is not available in ROS2 Jammy

### ISSUE THREAD

**Issue by AndyZe** [ros/ros_environment#32]
As commented [here](https://github.com/ros-industrial/industrial_ci/issues/782):

```
  $ sudo apt-get -qq install -y --no-upgrade --no-install-recommends ros-rolling-ros-environment | grep -E 'Setting up' 
  E: Unable to locate package ros-rolling-ros-environment
  'sudo apt-get -qq install -y --no-upgrade --no-install-recommends ros-rolling-ros-environment | grep -E 'Setting up' ' returned with 100
```

**Comment by nuclearsandwich** [comment]
@AndyZe I see from the issue title that you're on Ubuntu Jammy but for completeness can you please include the output of
```
cat /etc/os-release
```

As well as information about the ROS apt repositories configured on your system. The current status for Rolling shows that the [ros_environment package is available for that distribution on Ubuntu Jammy](http://repo.ros2.org/status_page/ros_rolling_default.html?q=ros_environment).

**Comment by AndyZe** [comment]
OK, thanks. My problem is, this is the [industrial_ci](https://github.com/ros-industrial/industrial_ci/issues/782) repo which MoveIt2 uses to run CI. I'm far from an expert on how it works or how I would check the ROS apt repositories. Thanks for at least indicating that it is not caused by the binary being unavailable.

**Comment by AndyZe** [comment]
Comment from [here](https://github.com/ros-industrial/industrial_ci/issues/782#issuecomment-1114337560):

```
apt update is not even working in a normal ubuntu:jammy image
(Try docker run -it --rm ubuntu:jammy apt update)

So I guess there is not much we can do.
```

**Comment by AndyZe** [comment]
I'm just going to close this. It seems like the problem is downstream somehow.
