### ISSUE TITLE
ROS_PYTHON_VERSION should be set for all distros

### ISSUE THREAD

**Issue by mikaelarguedas** [ros/ros_environment#7]
As per [REP149](https://github.com/ros-infrastructure/rep/blob/a445fe475775ff917ebf9b714c4a81649bbad99b/rep-0149.rst). ROS_PYTHON_VERSION should be provided. With a value of `2` for ROS 1 distributions (that can be overridden by users wanting to use Python3), and a value of `3` for ROS 2 distributions and should *not* be overridden.

**Comment by mikaelarguedas** [comment]
PRs to address this in [lunar](https://github.com/ros/ros_environment/pull/8) and [kinetic](https://github.com/ros/ros_environment/pull/9).

Not sure what the plan is for indigo though, feedback welcome

**Comment by tfoote** [comment]
Indigo is old enough that making this change doesn't make sense. It does require that anything relying on this environment be forked post indigo. But as implementations will be new, I think that's reasonable as we're in the final year of a 5 year cycle for Trust.

**Comment by mikaelarguedas** [comment]
Sounds good to me, closing this then
